sudo: false

language: go

go:
  - "1.13"
  - "1.14"
  - "1.15"

install:
  - "go version"
  - "go env"
  - "mkdir -p $GOPATH/bin"

script:
  - "make test vet"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
