sudo: false

language: go

go:
  - "1.20"
  - "1.19"
  - "1.18"

install:
  - "go version"
  - "go env"
  - "mkdir -p $GOPATH/bin"

script:
  - "make test vet"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
