#! /usr/bin/python

# Python imports
from os.path import join, abspath, dirname
import sys

# Support multiple installations (aids in development too)
sys.path.insert(0, join(abspath(dirname(__file__)), '..'))

from notable import app
app.main()
