name: Go package

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.20.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Go version
        run: go version

      - name: Go env
        run: go env

      - name: Test
        run: make test vet

      - name: Code coverage
        run: "bash <(curl -s https://codecov.io/bash)"
